parameters:
#    friend_groups.example.class: Core\FriendGroupsBundle\Example

services:
#    friend_groups.example:
#        class: %friend_groups.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
