<?php

namespace Core\FriendGroupsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendListsRepository extends EntityRepository
{
}
