core_blog:
    resource: "@CoreBlogBundle/Resources/config/routing.yml"

app_gallery:
    resource: "@CoreGalleryBundle/Resources/config/routing.yml"
    prefix:   /

app_user:
    resource: "@CoreUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /api

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /api/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /api/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /api/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /api/profile

users:
    type: rest
    resource: Core\UserBundle\Controller\UsersController
    prefix : /api

