core_comment:
    resource: "@CoreCommentBundle/Resources/config/routing.yml"

core_friendList:
    resource: "@CoreFriendListBundle/Resources/config/routing.yml"
    prefix:   /

core_blog:
    resource: "@CoreBlogBundle/Resources/config/routing.yml"
    prefix:   /

app_gallery:
    resource: "@CoreGalleryBundle/Resources/config/routing.yml"

app_user:
    resource: "@CoreUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /api

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /api/profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /api/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /api/profile

users:
    type: rest
    resource: Core\UserBundle\Controller\UsersController
    prefix : /api
blogs:
    type: rest
    resource: Core\BlogBundle\Controller\BlogsController
    prefix : /api
comments:
    type: rest
    resource: Core\CommentBundle\Controller\CommentsController
    prefix : /api
