parameters:
#    core_message.example.class: Core\MessageBundle\Example

services:
#    core_message.example:
#        class: %core_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
