#Routing Gallery
core_comment_blog_homepage:
    path:     /comment/post/{postId}
    defaults: { _controller: CoreCommentBundle:Comment:index }

core_comment_photo_homepage:
    path:     /comment/photo/{photoId}
    defaults: { _controller: CoreCommentBundle:Comment:index }

#Routing COMMENT
core_comment_all:
    path:     /comment/all
    defaults: { _controller: CoreCommentBundle:Comment:indexAll }

core_comment_update:
    path:     /comment/update/{id}
    defaults: { _controller: CoreCommentBundle:Comment:update }

core_comment_delete:
    path:     /comment/delete/{id}
    defaults: { _controller: CoreCommentBundle:Comment:delete }


#Routing ADD PHOTO COMMENT
core_photo_comment_add:
    path:     /gallery/{albumSlug}/{photoId}/comment-add
    defaults: { _controller: CoreCommentBundle:Comment:add }

#Routing ADD BLOG COMMENT
core_post_comment_add:
    path:     /blog/{postId}/comment-add
    defaults: { _controller: CoreCommentBundle:Comment:add }
