<?php

namespace Core\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('created_at' => 'DESC'));
    }
}
