<?php

namespace Core\GameSessionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSessionRepository extends EntityRepository
{
}
