<?php

namespace Core\GalleryBundle\Entity\Gallery;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('created_at' => 'DESC'));
    }
}