#Routing Gallery

core_gallery_homepage:
    path:     /gallery
    defaults: { _controller: CoreGalleryBundle:Album:index }


#Routing Album

core_album_show:
    path:     /gallery/{id}
    defaults: { _controller: CoreGalleryBundle:Album:show }

core_album_create:
    path:     /gallery/album-create
    defaults: { _controller: CoreGalleryBundle:Album:add }

core_album_update:
    path:     /gallery/album-update/{id}
    defaults: { _controller: CoreGalleryBundle:Album:update }

core_album_delete:
    path:     /gallery/album-delete/{id}
    defaults: { _controller: CoreGalleryBundle:Album:delete }


#Routing PHOTO

core_photo_show:
    path:     /gallery/{albumId}/{id}
    defaults: { _controller: CoreGalleryBundle:Photo:show }

core_photo_create:
    path:     /gallery/{albumId}/photo-create
    defaults: { _controller: CoreGalleryBundle:Photo:add }

core_photo_update:
    path:     /gallery/{albumId}/photo-update/{id}
    defaults: { _controller: CoreGalleryBundle:Photo:update }

core_photo_delete:
    path:     /gallery/{albumId}/photo-delete/{id}
    defaults: { _controller: CoreGalleryBundle:Photo:delete }