#Routing Gallery

core_gallery_homepage:
    path:     /gallery
    defaults: { _controller: CoreGalleryBundle:Album:index }


#Routing Album
core_album_create:
    path:     /gallery/album-create
    defaults: { _controller: CoreGalleryBundle:Album:add }

core_album_show:
    path:     /gallery/{albumSlug}
    defaults: { _controller: CoreGalleryBundle:Album:show }

core_album_update:
    path:     /gallery/album-update/{albumSlug}
    defaults: { _controller: CoreGalleryBundle:Album:update }

core_album_delete:
    path:     /gallery/album-delete/{albumSlug}
    defaults: { _controller: CoreGalleryBundle:Album:delete }

#Routing PHOTO
core_photo_create:
    path:     /gallery/{albumSlug}/photo-create
    defaults: { _controller: CoreGalleryBundle:Photo:add }

core_photo_show:
    path:     /gallery/{albumSlug}/{photoSlug}
    defaults: { _controller: CoreGalleryBundle:Photo:show }

core_photo_update:
    path:     /gallery/{albumSlug}/photo-update/{photoSlug}
    defaults: { _controller: CoreGalleryBundle:Photo:update }

core_photo_delete:
    path:     /gallery/{albumSlug}/photo-delete/{photoSlug}
    defaults: { _controller: CoreGalleryBundle:Photo:delete }
