core_blog_homepage:
    path:     /blog
    defaults: { _controller: CoreBlogBundle:Blog:index }

#Routing POST

core_post_add:
    path:     /blog/add-post
    defaults: { _controller: CoreBlogBundle:Blog:addPost }

core_post_show:
    path:     /blog/{id}
    defaults: { _controller: CoreBlogBundle:Blog:showPost }

core_post_update:
    path:     /blog/update-post/{id}
    defaults: { _controller: CoreBlogBundle:Blog:updatePost }

core_post_delete:
    path:     /blog/delete-post/{id}
    defaults: { _controller: CoreBlogBundle:Blog:deletePost }

#Routing Comments

core_blog_comment_add:
    path:     /blog/{postId}/add-comment
    defaults: { _controller: CoreBlogBundle:Comment:add }

core_blog_comment_update:
    path:     /blog/{postId}/update-comment/{id}
    defaults: { _controller: CoreBlogBundle:Comment:update }

core_blog_comment_delete:
    path:     /blog/{postId}/delete-comment/{id}
    defaults: { _controller: CoreBlogBundle:Comment:delete }