core_blog_homepage:
    path:     /blog
    defaults: { _controller: CoreBlogBundle:Blog:index }

#Routing POST

core_post_add:
    path:     /blog/add-post
    defaults: { _controller: CoreBlogBundle:Blog:addPost }

core_post_show:
    path:     /blog/{id}
    defaults: { _controller: CoreBlogBundle:Blog:showPost }

core_post_update:
    path:     /blog/update-post/{id}
    defaults: { _controller: CoreBlogBundle:Blog:updatePost }

core_post_delete:
    path:     /blog/delete-post/{id}
    defaults: { _controller: CoreBlogBundle:Blog:deletePost }
